#第三回
##講師
- B2 好田

##TA
- B3 勝又
- B3 戸倉

In [ ]:
#環境構築用のセル

#PostgreSQL13 のインストールとサーバーの起動
!sudo cat > /etc/apt/sources.list.d/pgdg.list <<< "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main"
!sudo curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -  > /dev/null
!sudo apt-get -y -qq update > /dev/null
!sudo apt-get -y -qq install postgresql-13 > /dev/null
!sudo pg_ctlcluster 13 main start > /dev/null
!sudo -u postgres psql -U postgres --version

#Pagilaデータベースの作成、ユーザーpadwanの設定
!sudo -u postgres psql -U postgres -c "create database pagila;"
!sudo -u postgres psql -U postgres -c "create user padwan with superuser;"
!sudo -u postgres psql -U postgres -c "alter user padwan password 'padwan12345';"
!sudo -u postgres psql -U postgres -c "grant all privileges on database pagila to padwan;"
!sudo -u postgres psql -U postgres -c "grant pg_read_server_files to padwan;"
!sudo -u postgres psql -U postgres -c "grant pg_write_server_files to padwan;"

#PagilaのGitHubリポジトリをcloneし、Pagila設定用SQLファイルを実行する
!sudo mkdir /tmp/data
!git clone https://github.com/devrimgunduz/pagila.git /tmp/data/pagila
base = "/tmp/data/pagila/"
sql_names = ('pagila-schema.sql', 'pagila-data.sql')
for sql_name in sql_names:
   SQLFILE=base+sql_name
   !sudo cat $SQLFILE | sudo -u postgres psql -U postgres -d pagila
#SQL入力準備（以降は%%sqlに続く行にSQLを入力可能）
%load_ext sql
%config SqlMagic.autopandas = True
%sql postgresql://padwan:padwan12345@localhost:5432/pagila
!git clone https://github.com/appacademy/aa-sql-sql-zoo.git
!sudo -u postgres psql -U postgres -d pagila -a -f /content/aa-sql-sql-zoo/data/create_tables.sql

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  4812  100  4812    0     0   7571      0 --:--:-- --:--:-- --:--:--  7577
W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 12.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
psql (PostgreSQL) 13.12 (Ubuntu 13.12-1.pgdg22.04+1)
CREATE DATABASE
CREATE ROLE
ALTER ROLE
GRANT
GRANT ROLE
GRANT ROLE
Cloning into '/tmp/data/pagila'...
remote: Enumerating objects: 191, done.
remote: Counting objects: 100% (191/191), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 191 (delta 99), reused 143 (delta 70), pack-reused 0
Receiving objects: 100% (191/191), 39.92 MiB | 21.43 MiB/s, done.
Resolving deltas: 100% (99/99), done.
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
ALTER SCHEMA
CREATE DOMAIN
ALTER DOMAIN
CREATE TYPE
ALTER TYPE
CREATE DOMAIN
ALTER DOMAIN
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE SEQUENCE
ALTER TABLE
SET
SET
CREATE TABLE
ALTER TABLE
CREATE FUNCTION
ALTER FUNCTION
CREATE AGGREGATE
ALTER AGGREGATE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE MATERIALIZED VIEW
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE VIEW
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
REVOKE
GRANT
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
COPY 200
COPY 109
COPY 600
COPY 603
COPY 16
COPY 2
COPY 599
COPY 6
COPY 1000
COPY 5462
COPY 1000
COPY 4581
COPY 2
COPY 16044
COPY 723
COPY 2401
COPY 2713
COPY 2547
COPY 2677
COPY 2654
COPY 2334
 setval
--------
    200
(1 row)

 setval
--------
    605
(1 row)

 setval
--------
     16
(1 row)

 setval
--------
    600
(1 row)

 setval
--------
    109
(1 row)

 setval
--------
    599
(1 row)

 setval
--------
   1000
(1 row)

 setval
--------
   4581
(1 row)

 setval
--------
      6
(1 row)

 setval
--------
  32098
(1 row)

 setval
--------
  16049
(1 row)

 setval
--------
      2
(1 row)

 setval
--------
      2
(1 row)

Cloning into 'aa-sql-sql-zoo'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 39 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (39/39), 251.73 KiB | 10.94 MiB/s, done.
--
-- PostgreSQL database dump
--
SET statement_timeout = 0;
SET
SET lock_timeout = 0;
SET
SET client_encoding = 'UTF8';
SET
SET standard_conforming_strings = on;
SET
SET check_function_bodies = false;
SET
SET client_min_messages = warning;
SET
--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner:
--
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION
--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner:
--
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
COMMENT
SET search_path = public, pg_catalog;
SET
SET default_tablespace = '';
SET
SET default_with_oids = false;
SET
CREATE TABLE actors (
    id integer NOT NULL,
    name character varying
);
CREATE TABLE
CREATE TABLE albums (
    asin character(10) NOT NULL,
    title character varying(50),
    artist character varying(50),
    price decimal(10,2),
    rdate date,
    label character varying(50),
    rank integer
);
CREATE TABLE
CREATE TABLE castings (
    movie_id integer NOT NULL,
    actor_id integer NOT NULL,
    ord integer
);
CREATE TABLE
CREATE TABLE countries (
    name character varying NOT NULL,
    continent character varying,
    area integer,
    population bigint,
    gdp bigint
);
CREATE TABLE
CREATE TABLE depts (
    id integer NOT NULL,
    name character varying NOT NULL
);
CREATE TABLE
CREATE TABLE movies (
    id integer NOT NULL,
    title character varying,
    yr integer,
    score double precision,
    votes integer,
    director_id integer
);
CREATE TABLE
CREATE TABLE nobels (
    yr integer,
    subject character varying,
    winner character varying
);
CREATE TABLE
CREATE TABLE routes (
    num character varying NOT NULL,
    company character varying NOT NULL,
    pos integer NOT NULL,
    stop_id integer
);
CREATE TABLE
CREATE TABLE stops (
    id integer NOT NULL,
    name character varying
);
CREATE TABLE
CREATE TABLE styles (
    album character(10) NOT NULL,
    style character varying(100) NOT NULL
);
CREATE TABLE
CREATE TABLE teachers (
    id integer NOT NULL,
    dept_id integer,
    name character varying,
    phone integer,
    mobile character varying
);
CREATE TABLE
CREATE TABLE tracks (
    album character(10) NOT NULL,
    disk integer NOT NULL,
    posn integer NOT NULL,
    song character varying(255)
);
CREATE TABLE
COPY actors (id, name) FROM stdin;
COPY 5945
COPY albums (asin, title, artist, price, rdate, label, rank) FROM stdin;
COPY 171
COPY castings (movie_id, actor_id, ord) FROM stdin;
COPY 15713
COPY countries (name, continent, area, population, gdp) FROM stdin;
COPY 193
COPY depts (id, name) FROM stdin;
COPY 3
COPY movies (id, title, yr, score, votes, director_id) FROM stdin;
COPY 1845
COPY nobels (yr, subject, winner) FROM stdin;
COPY 816
COPY routes (num, company, pos, stop_id) FROM stdin;
COPY 1174
COPY stops (id, name) FROM stdin;
COPY 246
COPY styles (album, style) FROM stdin;
COPY 621
COPY teachers (id, dept_id, name, phone, mobile) FROM stdin;
COPY 6
COPY tracks (album, disk, posn, song) FROM stdin;
COPY 3267
ALTER TABLE ONLY actors
    ADD CONSTRAINT actor_pkey PRIMARY KEY (id);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30150: ERROR:  relation "actor_pkey" already exists
ALTER TABLE ONLY albums
    ADD CONSTRAINT albums_pkey PRIMARY KEY (asin);
ALTER TABLE
ALTER TABLE ONLY castings
    ADD CONSTRAINT casting_pkey PRIMARY KEY (movie_id, actor_id);
ALTER TABLE
ALTER TABLE ONLY countries
    ADD CONSTRAINT country_pkey PRIMARY KEY (name);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30159: ERROR:  relation "country_pkey" already exists
ALTER TABLE ONLY depts
    ADD CONSTRAINT dept_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY movies
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY routes
    ADD CONSTRAINT route_pkey PRIMARY KEY (num, company, pos);
ALTER TABLE
ALTER TABLE ONLY stops
    ADD CONSTRAINT stops_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY styles
    ADD CONSTRAINT styles_pkey PRIMARY KEY (album, style);
ALTER TABLE
ALTER TABLE ONLY teachers
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY tracks
    ADD CONSTRAINT tracks_pkey PRIMARY KEY (album, disk, posn);
ALTER TABLE
CREATE INDEX actor_name ON actors USING btree (name);
CREATE INDEX
CREATE INDEX casting_actor ON castings USING btree (actor_id);
CREATE INDEX
CREATE INDEX casting_movie ON castings USING btree (movie_id);
CREATE INDEX
CREATE INDEX casting_ord ON castings USING btree (ord);
CREATE INDEX
CREATE INDEX movie_title ON movies USING btree (title);
CREATE INDEX
CREATE INDEX teacher_dept ON teachers USING btree (dept_id);
CREATE INDEX
ALTER TABLE ONLY castings
    ADD CONSTRAINT casting_actorid_fkey FOREIGN KEY (actor_id) REFERENCES actors(id);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30195: ERROR:  there is no unique constraint matching given keys for referenced table "actors"
ALTER TABLE ONLY castings
    ADD CONSTRAINT casting_movieid_fkey FOREIGN KEY (movie_id) REFERENCES movies(id);
ALTER TABLE
ALTER TABLE ONLY movies
    ADD CONSTRAINT movie_director_fkey FOREIGN KEY (director_id) REFERENCES actors(id);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30201: ERROR:  there is no unique constraint matching given keys for referenced table "actors"
ALTER TABLE ONLY routes
    ADD CONSTRAINT route_stop_fkey FOREIGN KEY (stop_id) REFERENCES stops(id);
ALTER TABLE
ALTER TABLE ONLY styles
    ADD CONSTRAINT styles_album_fkey FOREIGN KEY (album) REFERENCES albums(asin);
ALTER TABLE
ALTER TABLE ONLY teachers
    ADD CONSTRAINT teacher_dept_fkey FOREIGN KEY (dept_id) REFERENCES depts(id);
ALTER TABLE
ALTER TABLE ONLY tracks
    ADD CONSTRAINT tracks_album_fkey FOREIGN KEY (album) REFERENCES albums(asin);
ALTER TABLE
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE
GRANT ALL ON SCHEMA public TO PUBLIC;
GRANT
--
-- PostgreSQL database dump complete
--

#この環境で使えるテーブル
- film_actor
- address
- city
- actor
- actor_info
- category
- country
- customer
- customer_list
- film_list
- nicer_but_slower_film_list
- film
- film_category
- inventory
- language
- sales_by_film_category
- rental
- sales_by_store
- staff_list
- payment
- store

#復習

問1. film テーブルから、映画の総置換費用（replacement_cost）を評価別に合計し、各評価カテゴリに対してその総合計を取得します

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
5 rows affected.

       sum rating
0  3678.06     PG
1  3945.05      R
2  3582.22      G
3  4549.77  PG-13
4  4228.90  NC-17

問2. film テーブルから、映画のデータを取得し、それらのデータを replacement_cost 列の値に基づいて昇順に並べ替えてください。

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
1000 rows affected.

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,888,THIN SAGEBRUSH,A Emotional Drama of a Husband And a Lumberjac...,2006,1,None,5,4.99,53,9.99,PG-13,2022-09-10 16:46:03.905795+00:00,[Behind the Scenes],'ancient':18 'build':14 'cat':16 'drama':5 'em...
1,656,PAPI NECKLACE,A Fanciful Display of a Car And a Monkey who m...,2006,1,None,3,0.99,128,9.99,PG,2022-09-10 16:46:03.905795+00:00,"[Trailers, Deleted Scenes, Behind the Scenes]",'ancient':18 'car':8 'display':5 'escap':14 'f...
2,686,PLUTO OLEANDER,A Action-Packed Reflection of a Car And a Moos...,2006,1,None,5,4.99,84,9.99,R,2022-09-10 16:46:03.905795+00:00,[Behind the Scenes],"'action':5 'action-pack':4 'car':10,18 'moos':..."
3,886,THEORY MERMAID,A Fateful Yarn of a Composer And a Monkey who ...,2006,1,None,5,0.99,184,9.99,PG-13,2022-09-10 16:46:03.905795+00:00,"[Deleted Scenes, Behind the Scenes]",'compos':8 'fate':4 'first':19 'man':20 'merma...
4,260,DUDE BLINDNESS,A Stunning Reflection of a Husband And a Lumbe...,2006,1,None,3,4.99,132,9.99,G,2022-09-10 16:46:03.905795+00:00,"[Trailers, Deleted Scenes]",'abandon':19 'blind':2 'dude':1 'face':14 'fri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,238,DOCTOR GRAIL,A Insightful Drama of a Womanizer And a Waitre...,2006,1,None,4,2.99,57,29.99,G,2022-09-10 16:46:03.905795+00:00,"[Trailers, Commentaries, Behind the Scenes]",'doctor':1 'drama':5 'forens':16 'grail':2 'in...
996,944,VIRGIN DAISY,A Awe-Inspiring Documentary of a Robot And a M...,2006,1,None,6,4.99,179,29.99,PG-13,2022-09-10 16:46:03.905795+00:00,"[Trailers, Behind the Scenes]",'administr':20 'awe':5 'awe-inspir':4 'daisi':...
997,81,BLINDNESS GUN,A Touching Drama of a Robot And a Dentist who ...,2006,1,None,6,4.99,103,29.99,PG-13,2022-09-10 16:46:03.905795+00:00,"[Trailers, Behind the Scenes]",'blind':1 'boat':20 'dentist':11 'drama':5 'gu...
998,994,WYOMING STORM,A Awe-Inspiring Panorama of a Robot And a Boat...,2006,1,None,6,4.99,100,29.99,PG-13,2022-09-10 16:46:03.905795+00:00,[Deleted Scenes],"'awe':5 'awe-inspir':4 'boat':13,23 'feminist'..."
999,483,JERICHO MULAN,A Amazing Yarn of a Hunter And a Butler who mu...,2006,1,None,3,2.99,171,29.99,NC-17,2022-09-10 16:46:03.905795+00:00,[Commentaries],'amaz':4 'boat':20 'boy':16 'butler':11 'defea...

問3. customerテーブルの全行に加え、activeカラムが1の時は‘ACTIVE’, 1でない場合は‘non-acrive’を1カラムとして追加表示してください。

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active,category
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
...,...,...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,True,2022-02-14,2022-02-15 09:57:20+00:00,1,ACTIVE

#1.JOIN

##1.1 INNER JOIN
INNER JOIN(内部結合)はそれぞれのテーブルのしていしたカラム(列)の値が一致するものだけを結合します

```
SELECT
 (*)
FROM
 (Table1)
INNER JOIN
 (Table2)
ON
 (結合の条件)
```

###例：

In [ ]:
%%sql
SELECT
 *
FROM
 film

 * postgresql://padwan:***@localhost:5432/pagila
1000 rows affected.

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,2022-09-10 16:46:03.905795+00:00,"[Deleted Scenes, Behind the Scenes]",'academi':1 'battl':15 'canadian':20 'dinosaur...
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,2022-09-10 16:46:03.905795+00:00,"[Trailers, Deleted Scenes]",'ace':1 'administr':9 'ancient':19 'astound':4...
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,2022-09-10 16:46:03.905795+00:00,"[Trailers, Deleted Scenes]",'adapt':1 'astound':4 'baloon':19 'car':11 'fa...
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,2022-09-10 16:46:03.905795+00:00,"[Commentaries, Behind the Scenes]",'affair':1 'chase':14 'documentari':5 'fanci':...
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,2022-09-10 16:46:03.905795+00:00,[Deleted Scenes],'african':1 'chef':11 'dentist':14 'documentar...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,None,6,0.99,183,9.99,G,2022-09-10 16:46:03.905795+00:00,"[Trailers, Behind the Scenes]",'administr':12 'boat':8 'boy':17 'databas':11 ...
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,None,4,0.99,179,14.99,NC-17,2022-09-10 16:46:03.905795+00:00,"[Trailers, Behind the Scenes]",'boat':22 'cat':11 'challeng':14 'drama':5 'ki...
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,None,6,0.99,105,10.99,NC-17,2022-09-10 16:46:03.905795+00:00,[Deleted Scenes],'boy':16 'canadian':19 'compos':8 'core':2 'fa...
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,2022-09-10 16:46:03.905795+00:00,"[Trailers, Deleted Scenes]",'ancient':19 'boat':11 'china':20 'discov':14 ...
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,None,3,4.99,50,18.99,NC-17,2022-09-10 16:46:03.905795+00:00,"[Trailers, Commentaries, Behind the Scenes]","'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona..."

In [ ]:
%%sql
SELECT
 *
FROM
 store

 * postgresql://padwan:***@localhost:5432/pagila
2 rows affected.

   store_id  manager_staff_id  address_id               last_update
0         1                 1           1 2022-02-15 09:57:12+00:00
1         2                 2           2 2022-02-15 09:57:12+00:00

In [ ]:
%%sql
SELECT
 *
FROM
 store
INNER JOIN
 customer
ON
 store.store_id=customer.store_id

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

,store_id,manager_staff_id,address_id,last_update,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,1,1,2022-02-15 09:57:12+00:00,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2022-02-14,2022-02-15 09:57:20+00:00,1
1,1,1,1,2022-02-15 09:57:12+00:00,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2022-02-14,2022-02-15 09:57:20+00:00,1
2,1,1,1,2022-02-15 09:57:12+00:00,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2022-02-14,2022-02-15 09:57:20+00:00,1
3,2,2,2,2022-02-15 09:57:12+00:00,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2022-02-14,2022-02-15 09:57:20+00:00,1
4,1,1,1,2022-02-15 09:57:12+00:00,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2022-02-14,2022-02-15 09:57:20+00:00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,1,1,1,2022-02-15 09:57:12+00:00,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,True,2022-02-14,2022-02-15 09:57:20+00:00,1
595,1,1,1,2022-02-15 09:57:12+00:00,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,True,2022-02-14,2022-02-15 09:57:20+00:00,1
596,1,1,1,2022-02-15 09:57:12+00:00,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,True,2022-02-14,2022-02-15 09:57:20+00:00,1
597,1,1,1,2022-02-15 09:57:12+00:00,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,True,2022-02-14,2022-02-15 09:57:20+00:00,1
598,2,2,2,2022-02-15 09:57:12+00:00,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,True,2022-02-14,2022-02-15 09:57:20+00:00,1

##1.2 OUTER JOIN

外部結合は、内部結合のようにそれぞれのテーブルの指定したカラム値(列の値)が一致するものを結合するのに加えて、どちらかのテーブルにしか存在しないものに関しても取得します。LEFT  OUTER JOINは左側のテーブルを軸にして外部結合を行い、RIGHT OUTER JOINは右側のテーブルを軸にして外部結合を行います。

###1.2.1 LEFT OUTER JOIN

```
SELECT
 (*)
FROM
 (Table1)
LEFT OUTER JOIN
 (Table2)
ON
 (結合の条件)
```

####例：

In [ ]:
%%sql
SELECT
 fc.category_id, fc.last_update, f.rental_rate, f.rating
FROM
 film_category fc
LEFT OUTER JOIN
 film f
ON
 fc.film_id=f.film_id
ORDER BY
category_id

 * postgresql://padwan:***@localhost:5432/pagila
1000 rows affected.

     category_id               last_update rental_rate rating
0              1 2022-02-15 10:07:09+00:00        0.99      R
1              1 2022-02-15 10:07:09+00:00        0.99      G
2              1 2022-02-15 10:07:09+00:00        2.99      R
3              1 2022-02-15 10:07:09+00:00        4.99     PG
4              1 2022-02-15 10:07:09+00:00        2.99  NC-17
..           ...                       ...         ...    ...
995           16 2022-02-15 10:07:09+00:00        0.99  PG-13
996           16 2022-02-15 10:07:09+00:00        2.99  NC-17
997           16 2022-02-15 10:07:09+00:00        2.99     PG
998           16 2022-02-15 10:07:09+00:00        0.99     PG
999           16 2022-02-15 10:07:09+00:00        4.99      G

[1000 rows x 4 columns]

###1.2.2 RIGHT OUTER JOIN

```
SELECT
 (*)
FROM
 (Table1)
RIGHT OUTER JOIN
 (Table2)
ON
 (結合の条件)
```

In [ ]:
%%sql
SELECT
 fc.category_id, fc.last_update, f.rental_rate, f.rating
FROM
 film_category fc
RIGHT OUTER JOIN
 film f
ON
 fc.film_id=f.film_id
ORDER BY
category_id

 * postgresql://padwan:***@localhost:5432/pagila
1000 rows affected.

     category_id               last_update rental_rate rating
0              1 2022-02-15 10:07:09+00:00        0.99      R
1              1 2022-02-15 10:07:09+00:00        0.99      G
2              1 2022-02-15 10:07:09+00:00        2.99      R
3              1 2022-02-15 10:07:09+00:00        4.99     PG
4              1 2022-02-15 10:07:09+00:00        2.99  NC-17
..           ...                       ...         ...    ...
995           16 2022-02-15 10:07:09+00:00        0.99  PG-13
996           16 2022-02-15 10:07:09+00:00        2.99  NC-17
997           16 2022-02-15 10:07:09+00:00        2.99     PG
998           16 2022-02-15 10:07:09+00:00        0.99     PG
999           16 2022-02-15 10:07:09+00:00        4.99      G

[1000 rows x 4 columns]

OUTER JOINを使用することで一致しないデータも含めて関連性のあるデータを取得できます。
データの補完や欠損データの確認に役立ちます。

|id|alphabet|    
|---|---|
|1|a|
|2|b|
|3|c|
|4|d|

|id|alphabet|
|---|---|
|1|d|
|2|e|
|5|f|
|6|g|

INNER JOINの場合：

|id|alphabet|id|alphabet|
|---|---|---|---|
|1|a|1|c|
|2|b|2|d|

LEFT OUTER JOINの場合：

|id|alphabet|id|alphabet|
|---|---|---|---|
|1|a|1|d|
|2|b|2|e|
|3|c|
|4|d|

RIGHT OUTER JOINの場合：

|id|alphabet|id|alphabet|
|---|---|---|---|
|1|a|1|d|
|2|b|2|e|
|||5|f|
|||6|g|

##演習問題

問１.
customer テーブルと customer_list テーブルをINNER JOINして、以下の情報を含む結果セットを取得してください。

- 顧客ID (customer_id)
- 顧客の姓(last_name)
- 顧客の名(first_name)
- 顧客の住所 (address)
- 郵便番号 (zip code)
- 電話番号 (phone)
- 都市 (city)
- 国 (country)

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

,customer_id,last_name,first_name,address,phone,city,country
0,1,SMITH,MARY,1913 Hanoi Way,28303384290,Sasebo,Japan
1,2,JOHNSON,PATRICIA,1121 Loja Avenue,838635286649,San Bernardino,United States
2,3,WILLIAMS,LINDA,692 Joliet Street,448477190408,Athenai,Greece
3,4,JONES,BARBARA,1566 Inegl Manor,705814003527,Myingyan,Myanmar
4,5,BROWN,ELIZABETH,53 Idfu Parkway,10655648674,Nantou,Taiwan
...,...,...,...,...,...,...,...
594,595,GUNDERSON,TERRENCE,844 Bucuresti Place,935952366111,Jinzhou,China
595,596,FORSYTHE,ENRIQUE,1101 Bucuresti Boulevard,199514580428,Patras,Greece
596,597,DUGGAN,FREDDIE,1103 Quilmes Boulevard,644021380889,Sullana,Peru
597,598,DELVALLE,WADE,1331 Usak Boulevard,145308717464,Lausanne,Switzerland
598,599,CINTRON,AUSTIN,1325 Fukuyama Street,288241215394,Tieli,China

問2. customer テーブルと customer_list テーブルとcountryをINNER JOINして、各顧客の次の情報を含む結果セットを取得してください。

- 顧客ID (customer_id)
- 顧客の姓(last_name)
- 顧客の名(first_name)
- 顧客の国名 (country)
- 最終更新日時 (last_update)*斜体テキスト*

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active,...,address,zip code,phone,city,country,notes,sid,country_id,country,last_update
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1913 Hanoi Way,35200,28303384290,Sasebo,Japan,active,1,50,Japan,2022-02-15 09:44:00+00:00
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1121 Loja Avenue,17886,838635286649,San Bernardino,United States,active,1,103,United States,2022-02-15 09:44:00+00:00
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,692 Joliet Street,83579,448477190408,Athenai,Greece,active,1,39,Greece,2022-02-15 09:44:00+00:00
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1566 Inegl Manor,53561,705814003527,Myingyan,Myanmar,active,2,64,Myanmar,2022-02-15 09:44:00+00:00
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,53 Idfu Parkway,42399,10655648674,Nantou,Taiwan,active,1,92,Taiwan,2022-02-15 09:44:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,844 Bucuresti Place,36603,935952366111,Jinzhou,China,active,1,23,China,2022-02-15 09:44:00+00:00
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1101 Bucuresti Boulevard,97661,199514580428,Patras,Greece,active,1,39,Greece,2022-02-15 09:44:00+00:00
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1103 Quilmes Boulevard,52137,644021380889,Sullana,Peru,active,1,74,Peru,2022-02-15 09:44:00+00:00
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1331 Usak Boulevard,61960,145308717464,Lausanne,Switzerland,active,1,91,Switzerland,2022-02-15 09:44:00+00:00
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,True,2022-02-14,2022-02-15 09:57:20+00:00,1,...,1325 Fukuyama Street,27107,288241215394,Tieli,China,active,2,23,China,2022-02-15 09:44:00+00:00

問3. film テーブルと film_actor テーブルをRIGHT OUTER JOINして、以下の情報を含む結果セットを取得してください。

- 映画のタイトル (title)
- 出演した俳優のID (actor_id)
- 最終更新日時 (last_update)

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
5465 rows affected.

                      title  actor_id               last_update
0          ACADEMY DINOSAUR       1.0 2022-02-15 10:05:03+00:00
1      ANACONDA CONFESSIONS       1.0 2022-02-15 10:05:03+00:00
2               ANGELS LIFE       1.0 2022-02-15 10:05:03+00:00
3     BULWORTH COMMANDMENTS       1.0 2022-02-15 10:05:03+00:00
4             CHEAPER CLYDE       1.0 2022-02-15 10:05:03+00:00
...                     ...       ...                       ...
5460       WARDROBE PHANTOM     200.0 2022-02-15 10:05:03+00:00
5461         WRONG BEHAVIOR     200.0 2022-02-15 10:05:03+00:00
5462       SLACKER LIAISONS       NaN                       NaT
5463            FLIGHT LIES       NaN                       NaT
5464       DRUMLINE CYCLONE       NaN                       NaT

[5465 rows x 3 columns]

問4. film テーブル、film_category テーブル、film_actor テーブル、および language テーブルを結合し、以下の情報を含む結果セットを取得してください。

- 映画のタイトル (film.title)
-カテゴリID (film_category.category_id)
-出演した俳優のID (film_actor.actor_id)
-映画の言語 (language.name)

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
5465 rows affected.

,film_title,category_name,actor_id,language,film_last_update
0,ACADEMY DINOSAUR,6,1.0,English,2022-09-10 16:46:03.905795+00:00
1,ANACONDA CONFESSIONS,2,1.0,English,2022-09-10 16:46:03.905795+00:00
2,ANGELS LIFE,13,1.0,English,2022-09-10 16:46:03.905795+00:00
3,BULWORTH COMMANDMENTS,10,1.0,English,2022-09-10 16:46:03.905795+00:00
4,CHEAPER CLYDE,14,1.0,English,2022-09-10 16:46:03.905795+00:00
...,...,...,...,...,...
5460,WARDROBE PHANTOM,7,200.0,English,2022-09-10 16:46:03.905795+00:00
5461,WRONG BEHAVIOR,3,200.0,English,2022-09-10 16:46:03.905795+00:00
5462,SLACKER LIAISONS,7,NaN,English,2022-09-10 16:46:03.905795+00:00
5463,FLIGHT LIES,15,NaN,English,2022-09-10 16:46:03.905795+00:00
5464,DRUMLINE CYCLONE,16,NaN,English,2022-09-10 16:46:03.905795+00:00

問5.　顧客ごとに、その顧客が支払った合計金額を計算し、顧客IDの昇順で結果を表示して下さい

rentalとpaymentを使います

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

     customer_id total_payment
0              1       3797.76
1              2       3475.71
2              3       3529.24
3              4       1799.16
4              5       5495.56
..           ...           ...
594          595       3531.00
595          596       2708.16
596          597       2493.75
597          598       1843.16
598          599       1592.39

[599 rows x 2 columns]

#2. VIEW

テーブルの特定部分や複数テーブルを結合し、ユーザに必要な部分だけをあたかも一つのテーブルであるかのように見せるための、仮想的なテーブルの概念です。

CREATE VIEW (ビュー名) AS (定義)

##例:

In [ ]:
%%sql
SELECT
 *
FROM
 customer

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2022-02-14,2022-02-15 09:57:20+00:00,1
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2022-02-14,2022-02-15 09:57:20+00:00,1
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2022-02-14,2022-02-15 09:57:20+00:00,1
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2022-02-14,2022-02-15 09:57:20+00:00,1
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2022-02-14,2022-02-15 09:57:20+00:00,1
...,...,...,...,...,...,...,...,...,...,...
594,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,True,2022-02-14,2022-02-15 09:57:20+00:00,1
595,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,True,2022-02-14,2022-02-15 09:57:20+00:00,1
596,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,True,2022-02-14,2022-02-15 09:57:20+00:00,1
597,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,True,2022-02-14,2022-02-15 09:57:20+00:00,1
598,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,True,2022-02-14,2022-02-15 09:57:20+00:00,1

In [ ]:
%%sql
CREATE VIEW customer_email AS
SELECT
first_name, last_name, email
FROM
customer

 * postgresql://padwan:***@localhost:5432/pagila
Done.

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql
SELECT
*
FROM
customer_name

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

    first_name  last_name
0         MARY      SMITH
1     PATRICIA    JOHNSON
2        LINDA   WILLIAMS
3      BARBARA      JONES
4    ELIZABETH      BROWN
..         ...        ...
594   TERRENCE  GUNDERSON
595    ENRIQUE   FORSYTHE
596    FREDDIE     DUGGAN
597       WADE   DELVALLE
598     AUSTIN    CINTRON

[599 rows x 2 columns]

テーブルの内容を変更したい場合、

**CREATE OR REPLACE VIEW ビュー名 AS 定義**

を用いて変更します。

##例:

In [ ]:
%%sql
CREATE OR REPLACE VIEW customer_name AS
SELECT
first_name, last_name, email
FROM
customer;

 * postgresql://padwan:***@localhost:5432/pagila
Done.

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql
SELECT
*
FROM
customer_name

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

    first_name  last_name                                  email
0         MARY      SMITH          MARY.SMITH@sakilacustomer.org
1     PATRICIA    JOHNSON    PATRICIA.JOHNSON@sakilacustomer.org
2        LINDA   WILLIAMS      LINDA.WILLIAMS@sakilacustomer.org
3      BARBARA      JONES       BARBARA.JONES@sakilacustomer.org
4    ELIZABETH      BROWN     ELIZABETH.BROWN@sakilacustomer.org
..         ...        ...                                    ...
594   TERRENCE  GUNDERSON  TERRENCE.GUNDERSON@sakilacustomer.org
595    ENRIQUE   FORSYTHE    ENRIQUE.FORSYTHE@sakilacustomer.org
596    FREDDIE     DUGGAN      FREDDIE.DUGGAN@sakilacustomer.org
597       WADE   DELVALLE       WADE.DELVALLE@sakilacustomer.org
598     AUSTIN    CINTRON      AUSTIN.CINTRON@sakilacustomer.org

[599 rows x 3 columns]

作ったテーブルを消去するためには、

DROP VIEW テーブル名

で消去します。

##例:

In [ ]:
%%sql
DROP VIEW customer_name

 * postgresql://padwan:***@localhost:5432/pagila
Done.

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql
SELECT
*
FROM
customer_name

 * postgresql://padwan:***@localhost:5432/pagila
(psycopg2.errors.UndefinedTable) relation "customer_name" does not exist
LINE 4: customer_name
        ^

[SQL: SELECT
*
FROM
customer_name]
(Background on this error at: https://sqlalche.me/e/20/f405)

##演習問題

以下の列を含む新しいビュー（カスタマービュー）を作成してください。

- 顧客ID (customer_id)
- 顧客の姓(last_name)
- 顧客の名(first_name)
- メールアドレス (email)

それを表示させてください

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
Done.

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql
SELECT
*
FROM
customer_view

 * postgresql://padwan:***@localhost:5432/pagila
599 rows affected.

     customer_id first_name  last_name                                  email
0              1       MARY      SMITH          MARY.SMITH@sakilacustomer.org
1              2   PATRICIA    JOHNSON    PATRICIA.JOHNSON@sakilacustomer.org
2              3      LINDA   WILLIAMS      LINDA.WILLIAMS@sakilacustomer.org
3              4    BARBARA      JONES       BARBARA.JONES@sakilacustomer.org
4              5  ELIZABETH      BROWN     ELIZABETH.BROWN@sakilacustomer.org
..           ...        ...        ...                                    ...
594          595   TERRENCE  GUNDERSON  TERRENCE.GUNDERSON@sakilacustomer.org
595          596    ENRIQUE   FORSYTHE    ENRIQUE.FORSYTHE@sakilacustomer.org
596          597    FREDDIE     DUGGAN      FREDDIE.DUGGAN@sakilacustomer.org
597          598       WADE   DELVALLE       WADE.DELVALLE@sakilacustomer.org
598          599     AUSTIN    CINTRON      AUSTIN.CINTRON@sakilacustomer.org

[599 rows x 4 columns]

問２　film テーブルから、以下の情報を含む新しいFilmInfoを作成してください。

- 映画のタイトル (title)
- 映画の説明 (description)
- 公開年 (release_year)
- 貸し出し期間 (rental_duration)
- 貸し出し料金 (rental_rate)
- 映画の長さ (length)
- 交換コスト (replacement_cost)
- 映画の評価 (rating)

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
(psycopg2.errors.DuplicateTable) relation "filminfo" already exists

[SQL: CREATE VIEW FilmInfo AS
SELECT
    title,
    description,
    release_year,
    rental_duration,
    rental_rate,
    length,
    replacement_cost,
    rating
FROM film;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql
SELECT
*
FROM
FilmInfo

 * postgresql://padwan:***@localhost:5432/pagila
1000 rows affected.

,title,description,release_year,rental_duration,rental_rate,length,replacement_cost,rating
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,6,0.99,86,20.99,PG
1,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,3,4.99,48,12.99,G
2,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,7,2.99,50,18.99,NC-17
3,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,5,2.99,117,26.99,G
4,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,6,2.99,130,22.99,G
...,...,...,...,...,...,...,...,...
995,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,6,0.99,183,9.99,G
996,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,4,0.99,179,14.99,NC-17
997,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,6,0.99,105,10.99,NC-17
998,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,5,2.99,101,28.99,R
999,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,3,4.99,50,18.99,NC-17

問３. sales_by_store テーブルと staff_list テーブルを結合して、各店舗の売上情報とその店舗の責任者の情報を含む staff_information を作成し、id 列で昇順に並べ替えて下さい。

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
Done.

Empty DataFrame
Columns: []
Index: []

#3. Limit

```
SELECT
(*)
FROM
(テーブル名)
LIMIT
(取得する行数)
```

##例：

In [ ]:
%%sql
SELECT
*
FROM
customer
LIMIT
10

 * postgresql://padwan:***@localhost:5432/pagila
10 rows affected.

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2022-02-14,2022-02-15 09:57:20+00:00,1
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2022-02-14,2022-02-15 09:57:20+00:00,1
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2022-02-14,2022-02-15 09:57:20+00:00,1
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2022-02-14,2022-02-15 09:57:20+00:00,1
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2022-02-14,2022-02-15 09:57:20+00:00,1
5,6,2,JENNIFER,DAVIS,JENNIFER.DAVIS@sakilacustomer.org,10,True,2022-02-14,2022-02-15 09:57:20+00:00,1
6,7,1,MARIA,MILLER,MARIA.MILLER@sakilacustomer.org,11,True,2022-02-14,2022-02-15 09:57:20+00:00,1
7,8,2,SUSAN,WILSON,SUSAN.WILSON@sakilacustomer.org,12,True,2022-02-14,2022-02-15 09:57:20+00:00,1
8,9,2,MARGARET,MOORE,MARGARET.MOORE@sakilacustomer.org,13,True,2022-02-14,2022-02-15 09:57:20+00:00,1
9,10,1,DOROTHY,TAYLOR,DOROTHY.TAYLOR@sakilacustomer.org,14,True,2022-02-14,2022-02-15 09:57:20+00:00,1

開始位置を変更したい場合は、OFFSETを用いて
```
SELECT
*
FROM
テーブル名
LIMIT
取得する行数
OFFSET
開始位置
```
となります

##例：

In [ ]:
%%sql
SELECT
*
FROM
customer
LIMIT
10
OFFSET
5

 * postgresql://padwan:***@localhost:5432/pagila
10 rows affected.

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,6,2,JENNIFER,DAVIS,JENNIFER.DAVIS@sakilacustomer.org,10,True,2022-02-14,2022-02-15 09:57:20+00:00,1
1,7,1,MARIA,MILLER,MARIA.MILLER@sakilacustomer.org,11,True,2022-02-14,2022-02-15 09:57:20+00:00,1
2,8,2,SUSAN,WILSON,SUSAN.WILSON@sakilacustomer.org,12,True,2022-02-14,2022-02-15 09:57:20+00:00,1
3,9,2,MARGARET,MOORE,MARGARET.MOORE@sakilacustomer.org,13,True,2022-02-14,2022-02-15 09:57:20+00:00,1
4,10,1,DOROTHY,TAYLOR,DOROTHY.TAYLOR@sakilacustomer.org,14,True,2022-02-14,2022-02-15 09:57:20+00:00,1
5,11,2,LISA,ANDERSON,LISA.ANDERSON@sakilacustomer.org,15,True,2022-02-14,2022-02-15 09:57:20+00:00,1
6,12,1,NANCY,THOMAS,NANCY.THOMAS@sakilacustomer.org,16,True,2022-02-14,2022-02-15 09:57:20+00:00,1
7,13,2,KAREN,JACKSON,KAREN.JACKSON@sakilacustomer.org,17,True,2022-02-14,2022-02-15 09:57:20+00:00,1
8,14,2,BETTY,WHITE,BETTY.WHITE@sakilacustomer.org,18,True,2022-02-14,2022-02-15 09:57:20+00:00,1
9,15,1,HELEN,HARRIS,HELEN.HARRIS@sakilacustomer.org,19,True,2022-02-14,2022-02-15 09:57:20+00:00,1

##演習問題

問１. FilmInfoから1から15行目のデータを表示してください。

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
15 rows affected.

,title,description,release_year,rental_duration,rental_rate,length,replacement_cost,rating
0,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,6,0.99,86,20.99,PG
1,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,3,4.99,48,12.99,G
2,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,7,2.99,50,18.99,NC-17
3,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,5,2.99,117,26.99,G
4,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,6,2.99,130,22.99,G
5,AGENT TRUMAN,A Intrepid Panorama of a Robot And a Boy who m...,2006,3,2.99,169,17.99,PG
6,AIRPLANE SIERRA,A Touching Saga of a Hunter And a Butler who m...,2006,6,4.99,62,28.99,PG-13
7,AIRPORT POLLOCK,A Epic Tale of a Moose And a Girl who must Con...,2006,6,4.99,54,15.99,R
8,ALABAMA DEVIL,A Thoughtful Panorama of a Database Administra...,2006,3,2.99,114,21.99,PG-13
9,ALADDIN CALENDAR,A Action-Packed Tale of a Man And a Lumberjack...,2006,6,4.99,63,24.99,NC-17
10,ALAMO VIDEOTAPE,A Boring Epistle of a Butler And a Cat who mus...,2006,6,0.99,126,16.99,G
11,ALASKA PHANTOM,A Fanciful Saga of a Hunter And a Pastry Chef ...,2006,6,0.99,136,22.99,PG
12,DATE SPEED,A Touching Saga of a Composer And a Moose who ...,2006,4,0.99,104,19.99,R
13,ALI FOREVER,A Action-Packed Drama of a Dentist And a Croco...,2006,4,4.99,150,21.99,PG
14,ALICE FANTASIA,A Emotional Drama of a A Shark And a Database ...,2006,6,0.99,94,23.99,NC-17

問２. customerからstore_id,first_name,last_name,emailを抽出して、100行目から150行目まで表示してください

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
50 rows affected.

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,101,1,PEGGY,MYERS,PEGGY.MYERS@sakilacustomer.org,105,True,2022-02-14,2022-02-15 09:57:20+00:00,1
1,102,1,CRYSTAL,FORD,CRYSTAL.FORD@sakilacustomer.org,106,True,2022-02-14,2022-02-15 09:57:20+00:00,1
2,103,1,GLADYS,HAMILTON,GLADYS.HAMILTON@sakilacustomer.org,107,True,2022-02-14,2022-02-15 09:57:20+00:00,1
3,104,1,RITA,GRAHAM,RITA.GRAHAM@sakilacustomer.org,108,True,2022-02-14,2022-02-15 09:57:20+00:00,1
4,105,1,DAWN,SULLIVAN,DAWN.SULLIVAN@sakilacustomer.org,109,True,2022-02-14,2022-02-15 09:57:20+00:00,1
5,106,1,CONNIE,WALLACE,CONNIE.WALLACE@sakilacustomer.org,110,True,2022-02-14,2022-02-15 09:57:20+00:00,1
6,107,1,FLORENCE,WOODS,FLORENCE.WOODS@sakilacustomer.org,111,True,2022-02-14,2022-02-15 09:57:20+00:00,1
7,108,1,TRACY,COLE,TRACY.COLE@sakilacustomer.org,112,True,2022-02-14,2022-02-15 09:57:20+00:00,1
8,109,2,EDNA,WEST,EDNA.WEST@sakilacustomer.org,113,True,2022-02-14,2022-02-15 09:57:20+00:00,1
9,110,2,TIFFANY,JORDAN,TIFFANY.JORDAN@sakilacustomer.org,114,True,2022-02-14,2022-02-15 09:57:20+00:00,1
10,111,1,CARMEN,OWENS,CARMEN.OWENS@sakilacustomer.org,115,True,2022-02-14,2022-02-15 09:57:20+00:00,1
11,112,2,ROSA,REYNOLDS,ROSA.REYNOLDS@sakilacustomer.org,116,True,2022-02-14,2022-02-15 09:57:20+00:00,1
12,113,2,CINDY,FISHER,CINDY.FISHER@sakilacustomer.org,117,True,2022-02-14,2022-02-15 09:57:20+00:00,1
13,114,2,GRACE,ELLIS,GRACE.ELLIS@sakilacustomer.org,118,True,2022-02-14,2022-02-15 09:57:20+00:00,1
14,115,1,WENDY,HARRISON,WENDY.HARRISON@sakilacustomer.org,119,True,2022-02-14,2022-02-15 09:57:20+00:00,1
15,116,1,VICTORIA,GIBSON,VICTORIA.GIBSON@sakilacustomer.org,120,True,2022-02-14,2022-02-15 09:57:20+00:00,1
16,117,1,EDITH,MCDONALD,EDITH.MCDONALD@sakilacustomer.org,121,True,2022-02-14,2022-02-15 09:57:20+00:00,1
17,118,1,KIM,CRUZ,KIM.CRUZ@sakilacustomer.org,122,True,2022-02-14,2022-02-15 09:57:20+00:00,1
18,119,1,SHERRY,MARSHALL,SHERRY.MARSHALL@sakilacustomer.org,123,True,2022-02-14,2022-02-15 09:57:20+00:00,1
19,120,2,SYLVIA,ORTIZ,SYLVIA.ORTIZ@sakilacustomer.org,124,True,2022-02-14,2022-02-15 09:57:20+00:00,1
20,121,1,JOSEPHINE,GOMEZ,JOSEPHINE.GOMEZ@sakilacustomer.org,125,True,2022-02-14,2022-02-15 09:57:20+00:00,1
21,122,1,THELMA,MURRAY,THELMA.MURRAY@sakilacustomer.org,126,True,2022-02-14,2022-02-15 09:57:20+00:00,1
22,123,2,SHANNON,FREEMAN,SHANNON.FREEMAN@sakilacustomer.org,127,True,2022-02-14,2022-02-15 09:57:20+00:00,1
23,124,1,SHEILA,WELLS,SHEILA.WELLS@sakilacustomer.org,128,True,2022-02-14,2022-02-15 09:57:20+00:00,0
24,125,1,ETHEL,WEBB,ETHEL.WEBB@sakilacustomer.org,129,True,2022-02-14,2022-02-15 09:57:20+00:00,1
25,126,1,ELLEN,SIMPSON,ELLEN.SIMPSON@sakilacustomer.org,130,True,2022-02-14,2022-02-15 09:57:20+00:00,1
26,127,2,ELAINE,STEVENS,ELAINE.STEVENS@sakilacustomer.org,131,True,2022-02-14,2022-02-15 09:57:20+00:00,1
27,128,1,MARJORIE,TUCKER,MARJORIE.TUCKER@sakilacustomer.org,132,True,2022-02-14,2022-02-15 09:57:20+00:00,1
28,129,1,CARRIE,PORTER,CARRIE.PORTER@sakilacustomer.org,133,True,2022-02-14,2022-02-15 09:57:20+00:00,1
29,130,1,CHARLOTTE,HUNTER,CHARLOTTE.HUNTER@sakilacustomer.org,134,True,2022-02-14,2022-02-15 09:57:20+00:00,1
30,131,2,MONICA,HICKS,MONICA.HICKS@sakilacustomer.org,135,True,2022-02-14,2022-02-15 09:57:20+00:00,1
31,132,2,ESTHER,CRAWFORD,ESTHER.CRAWFORD@sakilacustomer.org,136,True,2022-02-14,2022-02-15 09:57:20+00:00,1
32,133,1,PAULINE,HENRY,PAULINE.HENRY@sakilacustomer.org,137,True,2022-02-14,2022-02-15 09:57:20+00:00,1
33,134,1,EMMA,BOYD,EMMA.BOYD@sakilacustomer.org,138,True,2022-02-14,2022-02-15 09:57:20+00:00,1
34,135,2,JUANITA,MASON,JUANITA.MASON@sakilacustomer.org,139,True,2022-02-14,2022-02-15 09:57:20+00:00,1
35,136,2,ANITA,MORALES,ANITA.MORALES@sakilacustomer.org,140,True,2022-02-14,2022-02-15 09:57:20+00:00,1
36,137,2,RHONDA,KENNEDY,RHONDA.KENNEDY@sakilacustomer.org,141,True,2022-02-14,2022-02-15 09:57:20+00:00,1
37,138,1,HAZEL,WARREN,HAZEL.WARREN@sakilacustomer.org,142,True,2022-02-14,2022-02-15 09:57:20+00:00,1
38,139,1,AMBER,DIXON,AMBER.DIXON@sakilacustomer.org,143,True,2022-02-14,2022-02-15 09:57:20+00:00,1
39,140,1,EVA,RAMOS,EVA.RAMOS@sakilacustomer.org,144,True,2022-02-14,2022-02-15 09:57:20+00:00,1
40,141,1,DEBBIE,REYES,DEBBIE.REYES@sakilacustomer.org,145,True,2022-02-14,2022-02-15 09:57:20+00:00,1
41,142,1,APRIL,BURNS,APRIL.BURNS@sakilacustomer.org,146,True,2022-02-14,2022-02-15 09:57:20+00:00,1
42,143,1,LESLIE,GORDON,LESLIE.GORDON@sakilacustomer.org,147,True,2022-02-14,2022-02-15 09:57:20+00:00,1
43,144,1,CLARA,SHAW,CLARA.SHAW@sakilacustomer.org,148,True,2022-02-14,2022-02-15 09:57:20+00:00,1
44,145,1,LUCILLE,HOLMES,LUCILLE.HOLMES@sakilacustomer.org,149,True,2022-02-14,2022-02-15 09:57:20+00:00,1
45,146,1,JAMIE,RICE,JAMIE.RICE@sakilacustomer.org,150,True,2022-02-14,2022-02-15 09:57:20+00:00,1
46,147,2,JOANNE,ROBERTSON,JOANNE.ROBERTSON@sakilacustomer.org,151,True,2022-02-14,2022-02-15 09:57:20+00:00,1
47,148,1,ELEANOR,HUNT,ELEANOR.HUNT@sakilacustomer.org,152,True,2022-02-14,2022-02-15 09:57:20+00:00,1
48,149,1,VALERIE,BLACK,VALERIE.BLACK@sakilacustomer.org,153,True,2022-02-14,2022-02-15 09:57:20+00:00,1
49,150,2,DANIELLE,DANIELS,DANIELLE.DANIELS@sakilacustomer.org,154,True,2022-02-14,2022-02-15 09:57:20+00:00,1

#総合問題

以下の列を含む新しいテーブル（film_view）を作成してください。

- 映画ID (film_id)
- タイトル (title)
- 説明 (description)
- カテゴリ名（film_category テーブルと結合してカテゴリ名を取得）
- 言語名（language テーブルと結合して言語名を取得）
- レンタル料金 (rental_rate)
- 再生時間 (length)
- 交換費用 (replacement_cost)
- 評価 (rating)
- 最終更新日時 (last_update)

In [ ]:
%%sql

 * postgresql://padwan:***@localhost:5432/pagila
Done.

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%sql
SELECT
*
FROM
film_view

 * postgresql://padwan:***@localhost:5432/pagila
(psycopg2.errors.UndefinedTable) relation "film_view" does not exist
LINE 4: film_view
        ^

[SQL: SELECT
*
FROM
film_view]
(Background on this error at: https://sqlalche.me/e/20/f405)

問2film_view ビューから、以下の条件を持つ映画を抽出してください。

- レンタル料金 (rental_rate) が2.99以上の映画。
- 映画の長さ (length) が120分以上の映画。
- 類似性の高い映画カテゴリ (category_id) が複数存在する映画。
- 総合評価 (rating) が 'PG-13' または 'R' の映画。
- 抽出する映画の数を5本に制限。

In [ ]:
%%sql

UsageError: Cell magic `%%sql` not found.