In [ ]:
#環境構築用のセル

#PostgreSQL13 のインストールとサーバーの起動
!sudo cat > /etc/apt/sources.list.d/pgdg.list <<< "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main"
!sudo curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -  > /dev/null
!sudo apt-get -y -qq update > /dev/null
!sudo apt-get -y -qq install postgresql-13 > /dev/null
!sudo pg_ctlcluster 13 main start > /dev/null
!sudo -u postgres psql -U postgres --version

#Pagilaデータベースの作成、ユーザーpadwanの設定
!sudo -u postgres psql -U postgres -c "create database pagila;"
!sudo -u postgres psql -U postgres -c "create user padwan with superuser;"
!sudo -u postgres psql -U postgres -c "alter user padwan password 'padwan12345';"
!sudo -u postgres psql -U postgres -c "grant all privileges on database pagila to padwan;"
!sudo -u postgres psql -U postgres -c "grant pg_read_server_files to padwan;"
!sudo -u postgres psql -U postgres -c "grant pg_write_server_files to padwan;"

#PagilaのGitHubリポジトリをcloneし、Pagila設定用SQLファイルを実行する
!sudo mkdir /tmp/data
!git clone https://github.com/devrimgunduz/pagila.git /tmp/data/pagila
base = "/tmp/data/pagila/"
sql_names = ('pagila-schema.sql', 'pagila-data.sql')
for sql_name in sql_names:
   SQLFILE=base+sql_name
   !sudo cat $SQLFILE | sudo -u postgres psql -U postgres -d pagila
#SQL入力準備（以降は%%sqlに続く行にSQLを入力可能）
%load_ext sql
%config SqlMagic.autopandas = True
%sql postgresql://padwan:padwan12345@localhost:5432/pagila
!git clone https://github.com/appacademy/aa-sql-sql-zoo.git
!sudo -u postgres psql -U postgres -d pagila -a -f /content/aa-sql-sql-zoo/data/create_tables.sql

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  4812  100  4812    0     0  14225      0 --:--:-- --:--:-- --:--:-- 14194
W: http://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 12.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
psql (PostgreSQL) 13.12 (Ubuntu 13.12-1.pgdg22.04+1)
CREATE DATABASE
CREATE ROLE
ALTER ROLE
GRANT
GRANT ROLE
GRANT ROLE
Cloning into '/tmp/data/pagila'...
remote: Enumerating objects: 191, done.
remote: Counting objects: 100% (191/191), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 191 (delta 99), reused 143 (delta 70), pack-reused 0
Receiving objects: 100% (191/191), 39.92 MiB | 20.62 MiB/s, done.
Resolving deltas: 100% (99/99), done.
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
ALTER SCHEMA
CREATE DOMAIN
ALTER DOMAIN
CREATE TYPE
ALTER TYPE
CREATE DOMAIN
ALTER DOMAIN
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE SEQUENCE
ALTER TABLE
SET
SET
CREATE TABLE
ALTER TABLE
CREATE FUNCTION
ALTER FUNCTION
CREATE AGGREGATE
ALTER AGGREGATE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE MATERIALIZED VIEW
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE VIEW
ALTER TABLE
CREATE VIEW
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
REVOKE
GRANT
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
COPY 200
COPY 109
COPY 600
COPY 603
COPY 16
COPY 2
COPY 599
COPY 6
COPY 1000
COPY 5462
COPY 1000
COPY 4581
COPY 2
COPY 16044
COPY 723
COPY 2401
COPY 2713
COPY 2547
COPY 2677
COPY 2654
COPY 2334
 setval
--------
    200
(1 row)

 setval
--------
    605
(1 row)

 setval
--------
     16
(1 row)

 setval
--------
    600
(1 row)

 setval
--------
    109
(1 row)

 setval
--------
    599
(1 row)

 setval
--------
   1000
(1 row)

 setval
--------
   4581
(1 row)

 setval
--------
      6
(1 row)

 setval
--------
  32098
(1 row)

 setval
--------
  16049
(1 row)

 setval
--------
      2
(1 row)

 setval
--------
      2
(1 row)

Cloning into 'aa-sql-sql-zoo'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 39 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (39/39), 251.73 KiB | 4.50 MiB/s, done.
--
-- PostgreSQL database dump
--
SET statement_timeout = 0;
SET
SET lock_timeout = 0;
SET
SET client_encoding = 'UTF8';
SET
SET standard_conforming_strings = on;
SET
SET check_function_bodies = false;
SET
SET client_min_messages = warning;
SET
--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner:
--
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION
--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner:
--
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
COMMENT
SET search_path = public, pg_catalog;
SET
SET default_tablespace = '';
SET
SET default_with_oids = false;
SET
CREATE TABLE actors (
    id integer NOT NULL,
    name character varying
);
CREATE TABLE
CREATE TABLE albums (
    asin character(10) NOT NULL,
    title character varying(50),
    artist character varying(50),
    price decimal(10,2),
    rdate date,
    label character varying(50),
    rank integer
);
CREATE TABLE
CREATE TABLE castings (
    movie_id integer NOT NULL,
    actor_id integer NOT NULL,
    ord integer
);
CREATE TABLE
CREATE TABLE countries (
    name character varying NOT NULL,
    continent character varying,
    area integer,
    population bigint,
    gdp bigint
);
CREATE TABLE
CREATE TABLE depts (
    id integer NOT NULL,
    name character varying NOT NULL
);
CREATE TABLE
CREATE TABLE movies (
    id integer NOT NULL,
    title character varying,
    yr integer,
    score double precision,
    votes integer,
    director_id integer
);
CREATE TABLE
CREATE TABLE nobels (
    yr integer,
    subject character varying,
    winner character varying
);
CREATE TABLE
CREATE TABLE routes (
    num character varying NOT NULL,
    company character varying NOT NULL,
    pos integer NOT NULL,
    stop_id integer
);
CREATE TABLE
CREATE TABLE stops (
    id integer NOT NULL,
    name character varying
);
CREATE TABLE
CREATE TABLE styles (
    album character(10) NOT NULL,
    style character varying(100) NOT NULL
);
CREATE TABLE
CREATE TABLE teachers (
    id integer NOT NULL,
    dept_id integer,
    name character varying,
    phone integer,
    mobile character varying
);
CREATE TABLE
CREATE TABLE tracks (
    album character(10) NOT NULL,
    disk integer NOT NULL,
    posn integer NOT NULL,
    song character varying(255)
);
CREATE TABLE
COPY actors (id, name) FROM stdin;
COPY 5945
COPY albums (asin, title, artist, price, rdate, label, rank) FROM stdin;
COPY 171
COPY castings (movie_id, actor_id, ord) FROM stdin;
COPY 15713
COPY countries (name, continent, area, population, gdp) FROM stdin;
COPY 193
COPY depts (id, name) FROM stdin;
COPY 3
COPY movies (id, title, yr, score, votes, director_id) FROM stdin;
COPY 1845
COPY nobels (yr, subject, winner) FROM stdin;
COPY 816
COPY routes (num, company, pos, stop_id) FROM stdin;
COPY 1174
COPY stops (id, name) FROM stdin;
COPY 246
COPY styles (album, style) FROM stdin;
COPY 621
COPY teachers (id, dept_id, name, phone, mobile) FROM stdin;
COPY 6
COPY tracks (album, disk, posn, song) FROM stdin;
COPY 3267
ALTER TABLE ONLY actors
    ADD CONSTRAINT actor_pkey PRIMARY KEY (id);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30150: ERROR:  relation "actor_pkey" already exists
ALTER TABLE ONLY albums
    ADD CONSTRAINT albums_pkey PRIMARY KEY (asin);
ALTER TABLE
ALTER TABLE ONLY castings
    ADD CONSTRAINT casting_pkey PRIMARY KEY (movie_id, actor_id);
ALTER TABLE
ALTER TABLE ONLY countries
    ADD CONSTRAINT country_pkey PRIMARY KEY (name);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30159: ERROR:  relation "country_pkey" already exists
ALTER TABLE ONLY depts
    ADD CONSTRAINT dept_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY movies
    ADD CONSTRAINT movie_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY routes
    ADD CONSTRAINT route_pkey PRIMARY KEY (num, company, pos);
ALTER TABLE
ALTER TABLE ONLY stops
    ADD CONSTRAINT stops_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY styles
    ADD CONSTRAINT styles_pkey PRIMARY KEY (album, style);
ALTER TABLE
ALTER TABLE ONLY teachers
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);
ALTER TABLE
ALTER TABLE ONLY tracks
    ADD CONSTRAINT tracks_pkey PRIMARY KEY (album, disk, posn);
ALTER TABLE
CREATE INDEX actor_name ON actors USING btree (name);
CREATE INDEX
CREATE INDEX casting_actor ON castings USING btree (actor_id);
CREATE INDEX
CREATE INDEX casting_movie ON castings USING btree (movie_id);
CREATE INDEX
CREATE INDEX casting_ord ON castings USING btree (ord);
CREATE INDEX
CREATE INDEX movie_title ON movies USING btree (title);
CREATE INDEX
CREATE INDEX teacher_dept ON teachers USING btree (dept_id);
CREATE INDEX
ALTER TABLE ONLY castings
    ADD CONSTRAINT casting_actorid_fkey FOREIGN KEY (actor_id) REFERENCES actors(id);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30195: ERROR:  there is no unique constraint matching given keys for referenced table "actors"
ALTER TABLE ONLY castings
    ADD CONSTRAINT casting_movieid_fkey FOREIGN KEY (movie_id) REFERENCES movies(id);
ALTER TABLE
ALTER TABLE ONLY movies
    ADD CONSTRAINT movie_director_fkey FOREIGN KEY (director_id) REFERENCES actors(id);
psql:/content/aa-sql-sql-zoo/data/create_tables.sql:30201: ERROR:  there is no unique constraint matching given keys for referenced table "actors"
ALTER TABLE ONLY routes
    ADD CONSTRAINT route_stop_fkey FOREIGN KEY (stop_id) REFERENCES stops(id);
ALTER TABLE
ALTER TABLE ONLY styles
    ADD CONSTRAINT styles_album_fkey FOREIGN KEY (album) REFERENCES albums(asin);
ALTER TABLE
ALTER TABLE ONLY teachers
    ADD CONSTRAINT teacher_dept_fkey FOREIGN KEY (dept_id) REFERENCES depts(id);
ALTER TABLE
ALTER TABLE ONLY tracks
    ADD CONSTRAINT tracks_album_fkey FOREIGN KEY (album) REFERENCES albums(asin);
ALTER TABLE
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE
GRANT ALL ON SCHEMA public TO PUBLIC;
GRANT
--
-- PostgreSQL database dump complete
--

#### この環境で使えるテーブル
適当に色々引っ張ってきたので遊んでみてください〜
- film_actor
- address
- city
- actor
- actor_info
- category
- country
- countries
- customer
- customer_list
- film_list
- nicer_but_slower_film_list
- film
- film_category
- inventory
- language
- sales_by_film_category
- rental
- sales_by_store
- staff_list
- payment
- store

### 講師
- B3 勝又
### TA
- B2 好田
- B3 戸倉

### 復習

In [ ]:
%%sql
-- 一旦データの中身を見てみよう
SELECT
  *
FROM
  countries

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

            name      continent     area  population           gdp
0    Afghanistan     South Asia   652225  26000000.0           NaN
1        Albania         Europe    28728   3200000.0  6.656000e+09
2        Algeria    Middle East  2400000  32900000.0  7.501200e+10
3        Andorra         Europe      468     64000.0           NaN
4         Angola         Africa  1250000  14500000.0  1.493500e+10
..           ...            ...      ...         ...           ...
188    Venezuela  South America   881050  26600000.0           NaN
189      Vietnam   Asia-Pacific   329247  83600000.0  4.598000e+10
190        Yemen    Middle East   536869  21500000.0  1.225500e+10
191       Zambia         Africa   752614  11000000.0  4.950000e+09
192     Zimbabwe         Africa   390759  12900000.0  6.192000e+09

[193 rows x 5 columns]

In [ ]:
%%sql
-- 南アジアの国名, 面積, 人口, GDPを取得してください

 * postgresql://padwan:***@localhost:5432/pagila
8 rows affected.

           name     area  population           gdp
0   Afghanistan   652225    26000000           NaN
1    Bangladesh   143998   152600000  6.714400e+10
2        Bhutan    38364     2400000  1.824000e+09
3         India  3100000  1100000000  6.820000e+11
4         Nepal   147181    26300000  6.838000e+09
5      Pakistan   796095   161100000  9.666000e+10
6     Sri Lanka    65610    19400000  1.959400e+10
7  The Maldives      298      338000  8.483800e+08

In [ ]:
%%sql
-- 一人当たりGDP (gdp_per_capita) が 30,000(おそらくドル)より大きい国の情報全てと一人当たりGDPの値を取得してください。取得計算式 as 〇〇の形で命名ができます。

 * postgresql://padwan:***@localhost:5432/pagila
16 rows affected.

,name,continent,area,population,gdp,gpd_per_capita
0,Austria,Europe,83871,8100000,261630000000,32300
1,Belgium,Europe,30528,10300000,319609000000,31030
2,Denmark,Europe,43098,5400000,219510000000,40650
3,Finland,Europe,338145,5200000,170508000000,32790
4,France,Europe,543965,60700000,1826463000000,30090
5,Germany,Europe,357027,82500000,2484900000000,30120
6,Iceland,Europe,103000,294000,11354280000,38620
7,Ireland,Europe,70182,4000000,137120000000,34280
8,Japan,Asia-Pacific,377864,127900000,4755322000000,37180
9,Luxembourg,Europe,2586,465000,26146950000,56230
10,Norway,Europe,323759,4600000,239338000000,52030
11,Sweden,Europe,449964,8900000,318353000000,35770
12,Switzerland,Europe,41284,7100000,342433000000,48230
13,The Netherlands,Europe,41864,16300000,516710000000,31700
14,United Kingdom,Europe,242514,59600000,2022824000000,33940
15,United States of America,North America,9800000,295000000,12213000000000,41400

## 1. ORDER BY

- ORDER 句

**ORDER BY**
- テーブルからSELECTでデータを取得するとき,「ORDER BY」を使うと、指定されたカラムを基準に並べ替えることができます。
- 複数指定することもでき、前に書いたカラムを優先してソートします
- 昇順（ASC）または降順（DESC）二つのソート方法があります。
- Nan, nullは一番大きな値として扱われます

In [ ]:
%%sql
-- population で ORDER BY してみよう
SELECT
  *
FROM
  countries
ORDER BY
  population

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

,name,continent,area,population,gdp
0,Nauru,Asia-Pacific,21,9.900000e+03,NaN
1,Tuvalu,Asia-Pacific,26,1.000000e+04,NaN
2,Palau,Asia-Pacific,508,2.000000e+04,NaN
3,San Marino,Europe,61,2.700000e+04,NaN
4,Monaco,Europe,2,3.200000e+04,NaN
...,...,...,...,...,...
188,Indonesia,Asia-Pacific,1900000,2.253000e+08,2.568420e+11
189,United States of America,North America,9800000,2.950000e+08,1.221300e+13
190,India,South Asia,3100000,1.100000e+09,6.820000e+11
191,China,Asia-Pacific,9600000,1.300000e+09,1.677000e+12
192,Vatican,Europe,0,NaN,NaN

In [ ]:
%%sql
-- population で 昇順に ORDER BY してみよう
SELECT
  *
FROM
  countries
ORDER BY
  population ASC

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

,name,continent,area,population,gdp
0,Nauru,Asia-Pacific,21,9.900000e+03,NaN
1,Tuvalu,Asia-Pacific,26,1.000000e+04,NaN
2,Palau,Asia-Pacific,508,2.000000e+04,NaN
3,San Marino,Europe,61,2.700000e+04,NaN
4,Monaco,Europe,2,3.200000e+04,NaN
...,...,...,...,...,...
188,Indonesia,Asia-Pacific,1900000,2.253000e+08,2.568420e+11
189,United States of America,North America,9800000,2.950000e+08,1.221300e+13
190,India,South Asia,3100000,1.100000e+09,6.820000e+11
191,China,Asia-Pacific,9600000,1.300000e+09,1.677000e+12
192,Vatican,Europe,0,NaN,NaN

In [ ]:
%%sql
-- population で 降順に ORDER BY してみよう
SELECT
  *
FROM
  countries
ORDER BY
  population DESC

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

,name,continent,area,population,gdp
0,Vatican,Europe,0,NaN,NaN
1,China,Asia-Pacific,9600000,1.300000e+09,1.677000e+12
2,India,South Asia,3100000,1.100000e+09,6.820000e+11
3,United States of America,North America,9800000,2.950000e+08,1.221300e+13
4,Indonesia,Asia-Pacific,1900000,2.253000e+08,2.568420e+11
...,...,...,...,...,...
188,Monaco,Europe,2,3.200000e+04,NaN
189,San Marino,Europe,61,2.700000e+04,NaN
190,Palau,Asia-Pacific,508,2.000000e+04,NaN
191,Tuvalu,Asia-Pacific,26,1.000000e+04,NaN
192,Nauru,Asia-Pacific,21,9.900000e+03,NaN

In [ ]:
%%sql
-- population で 複数のカラムで ORDER BY してみよう
SELECT
  *
FROM
  countries
ORDER BY
  continent, -- 名前等の場合はアルファベット順になる
  population ASC

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

                      name   continent     area    population           gdp
0               Seychelles      Africa      455  7.600000e+04           NaN
1    Sao Tome and Principe      Africa     1001  1.690000e+05  6.253000e+07
2               Cape Verde      Africa     4033  4.820000e+05  8.531400e+08
3        Equatorial Guinea      Africa    28051  5.210000e+05  4.845300e+08
4                 Djibouti      Africa    23200  7.210000e+05           NaN
..                     ...         ...      ...           ...           ...
188            Afghanistan  South Asia   652225  2.600000e+07           NaN
189                  Nepal  South Asia   147181  2.630000e+07  6.838000e+09
190             Bangladesh  South Asia   143998  1.526000e+08  6.714400e+10
191               Pakistan  South Asia   796095  1.611000e+08  9.666000e+10
192                  India  South Asia  3100000  1.100000e+09  6.820000e+11

[193 rows x 5 columns]

### 演習　ORDER BY 編

In [ ]:
%%sql
-- countriesのデータを continent (小さい順) → name (アルファベット順) → GDP大きい順番で並べ替えよう

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

             name   continent     area    population           gdp
0          Angola      Africa  1250000  1.450000e+07  1.493500e+10
1           Benin      Africa   112622  7.100000e+06  3.763000e+09
2        Botswana      Africa   581730  1.800000e+06  7.812000e+09
3    Burkina Faso      Africa   274200  1.380000e+07  4.968000e+09
4         Burundi      Africa    27816  7.300000e+06           NaN
..            ...         ...      ...           ...           ...
188         India  South Asia  3100000  1.100000e+09  6.820000e+11
189         Nepal  South Asia   147181  2.630000e+07  6.838000e+09
190      Pakistan  South Asia   796095  1.611000e+08  9.666000e+10
191     Sri Lanka  South Asia    65610  1.940000e+07  1.959400e+10
192  The Maldives  South Asia      298  3.380000e+05  8.483800e+08

[193 rows x 5 columns]

## 2. GROUP BY / HAVING / 集計関数

- GROUP 句

**GROUP BY**
  - 指定したカラムでグルーピングを行う
  - SELECTの中には<b>指定したカラム</b>と<b>集計関数</b>しか使えない

- 集計関数
  - 集計をするための関数

|集計関数|動作|
|---|---|
|COUNT(X)|カラムXの件数を返す、```*```で指定するとレコード数を返す|
|SUM(X)|カラムXの合計値を返す|
|AVG(X)|カラムXの平均値を返す|
|MAX(X)|カラムXの最大値を返す|
|MIN(X)|カラムXの最小値を返す|

- HAVING 句

**HAVING BY**
- `GROUP BY`句でグループ化した結果に対して条件を適用するための句。
- `WHERE`句は集約前の各行に対して条件を適用するのに対し、`HAVING`句は集約後のグループ全体に対して条件を適用するもの。
- 例として特定の条件を満たすグループだけを結果として取得する場合に使用するとかがあります。

### 1.1 COUNT

In [ ]:
%%sql
-- ヨーロッパの国数(正確にはEuropeとフラグがあるカラム数)
SELECT
  COUNT(*) as cnt
FROM
  countries
WHERE
  continent = 'Europe'

 * postgresql://padwan:***@localhost:5432/pagila
1 rows affected.

   cnt
0   48

In [ ]:
%%sql
-- 各大陸の国数 エラーになる例

SELECT
  continent,
  COUNT(*) as cnt
FROM
  countries

 * postgresql://padwan:***@localhost:5432/pagila
(psycopg2.errors.GroupingError) column "countries.continent" must appear in the GROUP BY clause or be used in an aggregate function
LINE 4:   continent,
          ^

[SQL: -- 各大陸の国数 エラーになる例

SELECT
  continent,
  COUNT(*) as cnt
FROM
  countries]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
%%sql
-- 各大陸の国数 正常実行
SELECT
  continent,
  COUNT(*) as cnt
FROM
  countries
GROUP BY
  continent

 * postgresql://padwan:***@localhost:5432/pagila
8 rows affected.

       continent  cnt
0  South America   12
1  North America    3
2     South Asia    8
3         Africa   47
4    Middle East   19
5         Europe   48
6   Asia-Pacific   36
7       Americas   20

### DISTINCT

**DISTINCT**
- 重複するデータを除去して、一意のデータだけを取得するためのキーワード。
- 一つ以上のカラムに適用することで、特定のカラムの組み合わせが一意になるように結果を取得することもできる。

In [ ]:
%%sql

SELECT
  COUNT(DISTINCT continent) continent_cnt,
  COUNT(continent) as cnt, -- 名前の付けたいときは as　アリ/ナシどちらでも良い
FROM
  countries

 * postgresql://padwan:***@localhost:5432/pagila
1 rows affected.

   continent_cnt  count
0              8    193

### 1.2 平均 AVG(column) ・ 1.3 合計 SUM(column)

In [ ]:
%%sql
-- ヨーロッパ内での平均,合計 人口/GDP
SELECT
  AVG(population) as avg_population,
  AVG(gdp) as avg_gdp,
  SUM(population) as sum_population,
  SUM(gdp) as sum_gdp
FROM
  countries
WHERE
  continent = 'Europe'

 * postgresql://padwan:***@localhost:5432/pagila
1 rows affected.

          avg_population                avg_gdp sum_population         sum_gdp
0  17404680.851063829787  321792061951.21951220      818020000  13193474540000

### 1.4 MAX, MIN 関数

In [ ]:
%%sql
-- GDP最高、最低値
SELECT
  Max(gdp),
  Min(gdp)
FROM
  countries

 * postgresql://padwan:***@localhost:5432/pagila
1 rows affected.

              max       min
0  12213000000000  62530000

### 1.4 Having

In [ ]:
%%sql
-- 各大陸の国数(10カ国以上) 正常実行
SELECT
  continent,
  COUNT(*) AS country_count
FROM
  countries
GROUP BY
  continent
HAVING
  COUNT(*) > 10

 * postgresql://padwan:***@localhost:5432/pagila
6 rows affected.

       continent  country_count
0  South America             12
1         Africa             47
2    Middle East             19
3         Europe             48
4   Asia-Pacific             36
5       Americas             20

### 演習　集計関数編

#### 演習1

In [ ]:
%%sql
-- actorsテーブルに登録されている人数を数えて

 * postgresql://padwan:***@localhost:5432/pagila
1 rows affected.

   count
0   5945

#### 演習2

In [ ]:
%%sql
-- movies テーブルから 各年に公開された映画数(num_of_movies)をカウントして表示して

 * postgresql://padwan:***@localhost:5432/pagila
75 rows affected.

      yr  num_of_movies
0   1989             53
1   1991             61
2   1945              2
3   1974             13
4   1943              1
..   ...            ...
70  1954             10
71  1959              7
72  1988             71
73  1964              9
74  1969             11

[75 rows x 2 columns]

#### 演習3

In [ ]:
%%sql
-- 1999年に発売されたアルバムのうち値段の最大、最小、平均を取得してください。 (有効数字4桁) 取得方法、日付の指定方法がわからない場合はGoogleで調べてみてください

 * postgresql://padwan:***@localhost:5432/pagila
1 rows affected.

  min_price max_price avg_price
0     13.28     14.99     14.30

#### 演習4

In [ ]:
%%sql
-- inventoryテーブルを利用して 各店にある映画の種類を取得してください。

 * postgresql://padwan:***@localhost:5432/pagila
2 rows affected.

   store_id  film_cnt
0         1       759
1         2       762

## 3. CASE
- <b>CASE</b>
  - SELECTの中で使う
  - 条件に応じた新しいカラムを宣言することができる
  - イメージとしてはIF文に近い

```sql
SELECT
  CASE
    WHEN (条件式1) THEN (出力1)
    WHEN (条件式2) THEN (出力2)
    WHEN (条件式3) THEN (出力3)
  END AS (カラム名)
FROM (テーブル名)
```

In [ ]:
%%sql

SELECT
  name,
  area,
  CASE
      WHEN area < 100000 THEN 'Small'
      WHEN area BETWEEN 100000 AND 500000 THEN 'Medium'
      ELSE 'Large'
  END as size_category
FROM countries;

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

            name     area size_category
0    Afghanistan   652225         Large
1        Albania    28728         Small
2        Algeria  2400000         Large
3        Andorra      468         Small
4         Angola  1250000         Large
..           ...      ...           ...
188    Venezuela   881050         Large
189      Vietnam   329247        Medium
190        Yemen   536869         Large
191       Zambia   752614         Large
192     Zimbabwe   390759        Medium

[193 rows x 3 columns]

### CASE 演習問題

In [ ]:
%%sql
--  movie テーブルからtitle, score, categoryを出力するSQLを記述してください。categoryカラムは scoreが 8より大きい場合 Excellent, 6から8の間は Good それ以外は Average とします

 * postgresql://padwan:***@localhost:5432/pagila
1845 rows affected.

                                               title  score   category
0                                          Star Wars    8.8  Excellent
1                          Shawshank Redemption, The    9.0  Excellent
2                                       Pulp Fiction    8.6  Excellent
3                                            Titanic    7.2       Good
4     Star Wars: Episode V - The Empire Strikes Back    8.6  Excellent
...                                              ...    ...        ...
1840                                       Barcelona    6.6       Good
1841                               Absence of Malice    6.7       Good
1842                      Milagro Beanfield War, The    6.7       Good
1843                            End of Violence, The    5.6    Average
1844                          Hollywood Knights, The    5.5    Average

[1845 rows x 3 columns]

## 3. Window 関数

### ウィンドウ関数と集計関数の違い
- ウィンドウ関数には、AVG・SUM・MAX・MINなどの集計関数と同じ関数がある。
- 集計関数との違いは、出力結果が異なる。
- 集計関数は、グループごとの、レコードの集約を行なった１行の結果を返す。
- ウィンドウ関数では、レコードの集約は行わず、入力と同じ数のレコードを返す。


### 3.1 Window関数で用いる句

#### 3.1.1 OVER句

**OVER**
- ウィンドウ関数を適用する範囲を指定する。
- PARTITION BYやORDER BYと組み合わせて使用することが多い。


---

#### 3.1.2 PARTITION BY句

**PARTITION BY**
- OVER句内で使用し、データを特定のカラムの値に基づいてグループ化（パーティション化）する。
- 各パーティション内でウィンドウ関数を独立して適用する。


---

#### 3.1.3 ORDER BY句

**ORDER BY**
- OVER句内で使用し、ウィンドウ内の行の順序を指定する。
- 例えば、LAG/LEADやRANKなどの関数で順序が重要な場合に使用する。

```sql
SELECT
  column_name,
  SUM(column_name) OVER () AS sum
  SUM(column_name) OVER (PARTITION BY partition_column)  AS partition_sum
  SUM(column_name) OVER (ORDER BY order_column)  AS order_sum
  SUM(column_name) OVER (PARTITION BY partition_column ORDER BY order_column) AS order_partition_sum
FROM table_name;
```

In [ ]:
%%sql
-- 大陸ごとのGDP最高、最低値　平均値をその国の名前、大陸名等と一緒に一括取得
SELECT
  name,
  continent,
  gdp,
  AVG(gdp) OVER (PARTITION BY continent),
  Max(gdp) OVER (PARTITION BY continent),
  Min(gdp) OVER (PARTITION BY continent)
FROM
  countries
GROUP BY
  continent, name, gdp

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

,name,continent,gdp,avg,max,min
0,Angola,Africa,1.493500e+10,11394338888.88888889,164439000000,62530000
1,Benin,Africa,3.763000e+09,11394338888.88888889,164439000000,62530000
2,Botswana,Africa,7.812000e+09,11394338888.88888889,164439000000,62530000
3,Burkina Faso,Africa,4.968000e+09,11394338888.88888889,164439000000,62530000
4,Burundi,Africa,NaN,11394338888.88888889,164439000000,62530000
...,...,...,...,...,...,...
188,India,South Asia,6.820000e+11,124986911428.57142857,682000000000,848380000
189,Nepal,South Asia,6.838000e+09,124986911428.57142857,682000000000,848380000
190,Pakistan,South Asia,9.666000e+10,124986911428.57142857,682000000000,848380000
191,Sri Lanka,South Asia,1.959400e+10,124986911428.57142857,682000000000,848380000
192,The Maldives,South Asia,8.483800e+08,124986911428.57142857,682000000000,848380000

### 3.2 集計関数を用いたWindow関数

### 3.3 集計関数で登場したもの以外の主なWindow関数
#### 3.3.1. LAG/LEAD

**LAG/LEAD**
- 現在の行の前後の行の値を取得する。
- LAGは前の行、LEADは次の行の値を返す。

```sql
SELECT
  LAG(column_name) OVER (ORDER BY order_column) AS prev_value,
  column_name,
  LEAD(column_name) OVER (ORDER BY order_column) AS next_value
FROM
  table_name;

```

In [ ]:
%%sql

SELECT
  name,
  LAG(name) OVER(ORDER BY id) as prev_stop,
  LEAD(name) OVER(ORDER BY id) as next_stop
FROM
  stops;

 * postgresql://padwan:***@localhost:5432/pagila
246 rows affected.

               name             prev_stop       next_stop
0          Aberlady                  None        Abington
1          Abington              Aberlady  Amisfield Park
2    Amisfield Park              Abington          Ancrum
3            Ancrum        Amisfield Park        Armadale
4          Armadale                Ancrum            ASDA
..              ...                   ...             ...
241        Whitburn  Wester Hailes Centre      Whitecraig
242      Whitecraig              Whitburn      Wilkieston
243      Wilkieston            Whitecraig      Willowbrae
244      Willowbrae            Wilkieston      Winchburgh
245      Winchburgh            Willowbrae            None

[246 rows x 3 columns]

#### 3.3.2. RANK

**RANK**
- 各行に順位を付ける。
- 同じ値の行は同じ順位を持ち、次の順位はスキップされる。

```sql
SELECT
  column_name,
  RANK() OVER (ORDER BY order_column DESC) AS rank
FROM
  table_name;
```

In [ ]:
%%sql
SELECT
  name,
  continent,
  gdp,
  RANK() OVER(PARTITION BY continent ORDER BY gdp DESC) as rank_within_continent
FROM
  countries
WHERE
  gdp IS NOT NULL

 * postgresql://padwan:***@localhost:5432/pagila
134 rows affected.

             name   continent           gdp  rank_within_continent
0    South Africa      Africa  164439000000                      1
1         Nigeria      Africa   50778000000                      2
2           Libya      Africa   25810000000                      3
3           Kenya      Africa   15088000000                      4
4          Angola      Africa   14935000000                      5
..            ...         ...           ...                    ...
129    Bangladesh  South Asia   67144000000                      3
130     Sri Lanka  South Asia   19594000000                      4
131         Nepal  South Asia    6838000000                      5
132        Bhutan  South Asia    1824000000                      6
133  The Maldives  South Asia     848380000                      7

[134 rows x 4 columns]

#### 3.3.3. ROW_NUMBER

**ROW_NUMBER**
- 各行に一意の順序を付ける。
- 同じ値でも順序はスキップされず、連続する番号が付けられる。

```sql
SELECT
  column_name,
  ROW_NUMBER() OVER (ORDER BY order_column DESC) AS row_num
FROM
  table_name;
```

In [ ]:
%%sql
SELECT
  title,
  rdate,
  ROW_NUMBER() OVER(ORDER BY rdate) as row_num
FROM
  albums

 * postgresql://padwan:***@localhost:5432/pagila
171 rows affected.

                                                 title       rdate  row_num
0                                       A Love Supreme  1964-12-09        1
1                                     Rubber Soul [UK]  1965-12-03        2
2                                        Revolver [UK]  1966-08-05        3
3                Sgt. Pepper's Lonely Hearts Club Band  1967-06-01        4
4                                           Abbey Road  1969-09-26        5
..                                                 ...         ...      ...
166                     For The Lonely18 Greatest Hits        None      167
167  Star Wars, A New HopeThe Original Motion Pictu...        None      168
168  Goodbye Yellow Brick Road [ORIGINAL RECORDING ...        None      169
169       Carreras Domingo Pavarotti ~ the three tenor        None      170
170  Wagner - Der Ring des Nibelungen (Ring Cycle) ...        None      171

[171 rows x 3 columns]

#### 演習問題

In [ ]:
%%sql
-- moviesテーブルより 映画タイトルとアルファベット順で前後のタイトル名を取得してください

In [ ]:
%%sql
-- 大陸ごとに、各国の人口密度（面積あたりの人口）に基づくランキングを取得してください (難)

 * postgresql://padwan:***@localhost:5432/pagila
193 rows affected.

,name,continent,population,area,population_density,rank_within_continent
0,Mauritius,Africa,1200000.0,2040,588.0,1
1,Comoros,Africa,812000.0,1862,436.0,2
2,Rwanda,Africa,8600000.0,26338,326.0,3
3,Burundi,Africa,7300000.0,27816,262.0,4
4,Sao Tome and Principe,Africa,169000.0,1001,168.0,5
...,...,...,...,...,...,...
188,Sri Lanka,South Asia,19400000.0,65610,295.0,4
189,Pakistan,South Asia,161100000.0,796095,202.0,5
190,Nepal,South Asia,26300000.0,147181,178.0,6
191,Bhutan,South Asia,2400000.0,38364,62.0,7
192,Afghanistan,South Asia,26000000.0,652225,39.0,8

In [ ]:
%%sql
-- 大陸ごとに、各国の人口密度（面積あたりの人口）が一番高い国を取得して

 * postgresql://padwan:***@localhost:5432/pagila
8 rows affected.

           name      continent  population     area  population_density
0     Mauritius         Africa     1200000     2040                 588
1      Barbados       Americas      272000      430                 632
2     Singapore   Asia-Pacific     4400000      660                6666
3        Monaco         Europe       32000        2               16000
4       Bahrain    Middle East      754000      717                1051
5        Mexico  North America   106400000  1960000                  54
6       Ecuador  South America    13400000   272045                  49
7  The Maldives     South Asia      338000      298                1134

### 4. その他
SQLの文法は順番が決まっています．
1. <b>select</b>　⇒　列(カラム)を指定
1. <b>from</b>　⇒　テーブルを指定
1. join　⇒　複数テーブルの結合処理（第3回で扱います）
1. <b>where</b>　⇒　絞り込み条件の指定
1. <b>group by</b>　⇒　グループ条件の指定
1. <b>having</b>　⇒　グループ化後の絞り込み条件の指定（今回は扱いません、whereと似た処理）
1. <b>order by</b>　⇒　ソート順の指定
1. limit　⇒　取得する行数の指定